// Indian states and union territories
export const INDIAN_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
];

// Major Indian cities
export const INDIAN_CITIES = [
  'Agra',
  'Ahmedabad',
  'Ajmer',
  'Aligarh',
  'Allahabad',
  'Amritsar',
  'Aurangabad',
  'Bangalore',
  'Bareilly',
  'Belgaum',
  'Bhavnagar',
  'Bhiwandi',
  'Bhopal',
  'Bhubaneswar',
  'Bikaner',
  'Bilaspur',
  'Bokaro',
  'Chandigarh',
  'Chennai',
  'Coimbatore',
  'Cuttack',
  'Dahod',
  'Davangere',
  'Dehradun',
  'Delhi',
  'Dhanbad',
  'Dharwad',
  'Durgapur',
  'Erode',
  'Faridabad',
  'Firozabad',
  'Ghaziabad',
  'Goa',
  'Gorakhpur',
  'Gulbarga',
  'Guntur',
  'Gurgaon',
  'Guwahati',
  'Gwalior',
  'Haldia',
  'Haridwar',
  'Howrah',
  'Hubli',
  'Hyderabad',
  'Indore',
  'Jabalpur',
  'Jaipur',
  'Jalandhar',
  'Jammu',
  'Jamnagar',
  'Jamshedpur',
  'Jhansi',
  'Jodhpur',
  'Kakinada',
  'Kannur',
  'Kanpur',
  'Kochi',
  'Kolhapur',
  'Kolkata',
  'Kollam',
  'Kozhikode',
  'Kurnool',
  'Lucknow',
  'Ludhiana',
  'Madurai',
  'Malappuram',
  'Mathura',
  'Meerut',
  'Moradabad',
  'Mumbai',
  'Mysore',
  'Nagpur',
  'Nanded',
  'Nashik',
  'Nellore',
  'Noida',
  'Palakkad',
  'Patna',
  'Pondicherry',
  'Pune',
  'Raipur',
  'Rajkot',
  'Ranchi',
  'Rourkela',
  'Salem',
  'Sangli',
  'Shimla',
  'Siliguri',
  'Solapur',
  'Srinagar',
  'Surat',
  'Thane',
  'Thiruvananthapuram',
  'Thrissur',
  'Tiruchirappalli',
  'Tirunelveli',
  'Tiruppur',
  'Ujjain',
  'Vadodara',
  'Varanasi',
  'Vijayawada',
  'Visakhapatnam',
  'Warangal',
];

// State to cities mapping (subset for demonstration)
export const STATE_CITIES_MAP = {
  Maharashtra: [
    'Mumbai',
    'Pune',
    'Nagpur',
    'Thane',
    'Nashik',
    'Aurangabad',
    'Solapur',
    'Amravati',
    'Kolhapur',
    'Sangli',
    'Akola',
    'Latur',
    'Dhule',
    'Ahmednagar',
    'Chandrapur',
    'Parbhani',
    'Ichalkaranji',
    'Jalgaon',
    'Bhusawal',
    'Panvel',
  ],
  Karnataka: [
    'Bangalore',
    'Mysore',
    'Hubli',
    'Dharwad',
    'Belgaum',
    'Davangere',
    'Bellary',
    'Bijapur',
    'Shimoga',
    'Tumkur',
    'Raichur',
    'Bidar',
    'Hospet',
    'Gadag',
    'Udupi',
  ],
  'Tamil Nadu': [
    'Chennai',
    'Coimbatore',
    'Madurai',
    'Tiruchirappalli',
    'Salem',
    'Tirunelveli',
    'Tiruppur',
    'Erode',
    'Vellore',
    'Thoothukudi',
    'Dindigul',
    'Thanjavur',
    'Ranipet',
    'Sivakasi',
    'Karur',
    'Udhagamandalam',
    'Hosur',
    'Nagercoil',
  ],
  Gujarat: [
    'Ahmedabad',
    'Surat',
    'Vadodara',
    'Rajkot',
    'Bhavnagar',
    'Jamnagar',
    'Junagadh',
    'Gandhinagar',
    'Anand',
    'Navsari',
    'Morbi',
    'Mahesana',
    'Bharuch',
    'Vapi',
    'Veraval',
    'Porbandar',
    'Godhra',
    'Bhuj',
  ],
  'Uttar Pradesh': [
    'Lucknow',
    'Kanpur',
    'Ghaziabad',
    'Agra',
    'Varanasi',
    'Meerut',
    'Allahabad',
    'Bareilly',
    'Aligarh',
    'Moradabad',
    'Saharanpur',
    'Gorakhpur',
    'Noida',
    'Firozabad',
    'Jhansi',
    'Muzaffarnagar',
    'Mathura',
    'Rampur',
    'Shahjahanpur',
  ],
  Rajasthan: [
    'Jaipur',
    'Jodhpur',
    'Kota',
    'Bikaner',
    'Ajmer',
    'Udaipur',
    'Bhilwara',
    'Alwar',
    'Bharatpur',
    'Sikar',
    'Pali',
    'Sri Ganganagar',
    'Kishangarh',
    'Baran',
    'Dhaulpur',
    'Tonk',
    'Beawar',
    'Hanumangarh',
  ],
  'West Bengal': [
    'Kolkata',
    'Howrah',
    'Durgapur',
    'Asansol',
    'Siliguri',
    'Bardhaman',
    'Malda',
    'Baharampur',
    'Habra',
    'Kharagpur',
    'Shantipur',
    'Dankuni',
    'Dhulian',
    'Raniganj',
    'Haldia',
    'Raiganj',
    'Krishnanagar',
    'Nabadwip',
  ],
  Telangana: [
    'Hyderabad',
    'Warangal',
    'Nizamabad',
    'Karimnagar',
    'Ramagundam',
    'Khammam',
    'Mahbubnagar',
    'Nalgonda',
    'Adilabad',
    'Suryapet',
    'Miryalaguda',
    'Jagtial',
    'Mancherial',
    'Nirmal',
    'Kothagudem',
  ],
  'Andhra Pradesh': [
    'Visakhapatnam',
    'Vijayawada',
    'Guntur',
    'Nellore',
    'Kurnool',
    'Kakinada',
    'Rajahmundry',
    'Tirupati',
    'Anantapur',
    'Kadapa',
    'Vizianagaram',
    'Eluru',
    'Ongole',
    'Nandyal',
    'Machilipatnam',
    'Adoni',
    'Tenali',
    'Chittoor',
  ],
  Kerala: [
    'Thiruvananthapuram',
    'Kochi',
    'Kozhikode',
    'Kollam',
    'Thrissur',
    'Alappuzha',
    'Palakkad',
    'Kannur',
    'Malappuram',
    'Kottayam',
    'Kasaragod',
    'Pathanamthitta',
    'Idukki',
    'Wayanad',
    'Ernakulam',
  ],
  Punjab: [
    'Ludhiana',
    'Amritsar',
    'Jalandhar',
    'Patiala',
    'Bathinda',
    'Mohali',
    'Firozpur',
    'Batala',
    'Pathankot',
    'Moga',
    'Abohar',
    'Malerkotla',
    'Khanna',
    'Phagwara',
    'Muktsar',
    'Barnala',
    'Rajpura',
    'Hoshiarpur',
  ],
};

// Get cities by state
export const getCitiesByState = stateName => {
  return STATE_CITIES_MAP[stateName] || [];
};

// Venue types for business classification
export const VENUE_TYPES = [
  'Banquet Hall',
  'Wedding Hall',
  'Conference Center',
  'Hotel',
  'Resort',
  'Community Center',
  'Restaurant',
  'Outdoor Venue',
  'Auditorium',
  'Convention Center',
  'Farm House',
  'Palace',
  'Heritage Venue',
  'Rooftop',
  'Garden',
  'Beach Resort',
  'Hill Station Resort',
  'Corporate Office Space',
  'Educational Institution',
  'Religious Center',
];

// Seating capacity ranges
export const SEATING_CAPACITY_RANGES = [
  { label: '1-50', min: 1, max: 50 },
  { label: '51-100', min: 51, max: 100 },
  { label: '101-200', min: 101, max: 200 },
  { label: '201-500', min: 201, max: 500 },
  { label: '501-1000', min: 501, max: 1000 },
  { label: '1000+', min: 1000, max: 10000 },
];

// Common amenities
export const COMMON_AMENITIES = [
  'Air Conditioning',
  'Parking',
  'Catering Service',
  'Sound System',
  'Lighting',
  'Stage',
  'Dance Floor',
  'Bridal Room',
  'Guest Rooms',
  'Valet Parking',
  'Security',
  'WiFi',
  'Generator Backup',
  'Garden Area',
  'Swimming Pool',
  'Spa Services',
  'Transportation',
  'Decoration Services',
  'Photography Services',
  'DJ Services',
];

// Event types
export const EVENT_TYPES = [
  'Wedding',
  'Reception',
  'Engagement',
  'Birthday Party',
  'Anniversary',
  'Corporate Event',
  'Conference',
  'Seminar',
  'Workshop',
  'Product Launch',
  'Exhibition',
  'Religious Ceremony',
  'Cultural Event',
  'Sports Event',
  'Graduation',
  'Reunion',
  'Baby Shower',
  'Kitty Party',
  'Festival Celebration',
  'Charity Event',
];
